# Generated by Django 2.2.4 on 2019-11-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='provider',
            field=models.CharField(choices=[('Rozetka', 'Rozetka'), ('Bookva', 'Bookva'), ('Globalbook', 'Globalbook'), ('Booklya', 'Booklya'), ('Yakaboo', 'Yakaboo')], max_length=100, null=True),
        ),
    ]
