# Generated by Django 2.2.4 on 2019-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20191110_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='provider',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
