# Generated by Django 2.2.6 on 2019-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_autor',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publishing_house',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Publication_date',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
