# Generated by Django 2.2.6 on 2019-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191227_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Publication_date',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
