# Generated by Django 2.2.4 on 2019-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191115_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[['Visa', 'Visa'], ['MasterCard', 'MasterCard']], max_length=100, null=True),
        ),
    ]
