# Generated by Django 2.2.4 on 2019-11-18 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('payments', '0003_payment_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[['In process', 'In process'], ['Ready', 'Ready']], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
