# Generated by Django 2.2.4 on 2019-11-23 09:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20191118_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglogs',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='billinglogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billinglogs',
            name='status',
            field=models.CharField(choices=[['In process', 'In process'], ['Ready', 'Ready']], max_length=100, null=True),
        ),
    ]
