# Generated by Django 2.2.4 on 2019-11-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('top_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
    ]
