# Generated by Django 2.2.4 on 2019-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='author',
            new_name='category_title',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='for_kids',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='genre',
        ),
    ]
