# Generated by Django 2.2.4 on 2019-11-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191110_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['indx'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='INDX',
            new_name='indx',
        ),
        migrations.AlterField(
            model_name='category',
            name='top_category',
            field=models.ForeignKey(blank=True, help_text='Enter a book top category (e.g. Language, Genre)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='catalog.Category'),
        ),
    ]
