# Generated by Django 2.2.4 on 2019-11-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191110_1922'),
        ('catalog', '0002_auto_20191114_1144'),
    ]

    operations = [
    ]
