# Generated by Django 2.2.6 on 2019-11-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productstatistics',
            table='statistics',
        ),
    ]
