# Generated by Django 2.2.6 on 2019-12-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
