# Generated by Django 2.2.6 on 2019-11-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_id',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='public_order_id',
            new_name='public_order',
        ),
    ]
