# Generated by Django 2.2.4 on 2019-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191030_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
