# Generated by Django 2.2.4 on 2019-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191102_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Some',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('order3', models.ManyToManyField(to='orders.OrderItem')),
            ],
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
