# Generated by Django 2.2.4 on 2019-11-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_person_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='spec',
        ),
        migrations.AddField(
            model_name='person',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Specialization'),
        ),
    ]
