# Generated by Django 2.2.4 on 2019-11-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191102_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
