# Generated by Django 2.2.4 on 2019-11-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191111_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
