# Generated by Django 2.2.4 on 2019-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191102_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='YOUR TEXT'),
        ),
    ]
