# Generated by Django 2.2.4 on 2019-10-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191031_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
