# Generated by Django 2.2.4 on 2019-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191113_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED_FOR_PROCESSING', 'Accepted for processing'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('DONE', 'Done')], max_length=100, null=True),
        ),
    ]
