# Generated by Django 2.2.4 on 2019-11-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191113_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit'), ('PP', 'PrivatPay'), ('POP', 'Pay of parts'), ('POC', 'Pay of card')], default='CR', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED_FOR_PROCESSING', 'Accepted for processing'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('DONE', 'Done')], default='AFP', max_length=100, null=True),
        ),
    ]
