# Generated by Django 2.2.4 on 2019-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery'),
        ('orders', '0012_auto_20191113_1605'),
    ]

    operations = [
    ]
