# Generated by Django 2.2.4 on 2019-11-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191115_1528'),
        ('orders', '0016_auto_20191116_1956'),
    ]

    operations = [
    ]
