# Generated by Django 2.2.4 on 2019-11-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191115_1528'),
        ('orders', '0022_auto_20191119_1510'),
    ]

    operations = [
    ]
