# Generated by Django 2.2.4 on 2019-11-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_merge_20191121_1733'),
        ('orders', '0018_auto_20191118_0750'),
    ]

    operations = [
    ]
