# Generated by Django 2.2.4 on 2019-12-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20191220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('PRIVAT_PAY', 'PrivatPay'), ('PAY_OF_PARTS', 'Pay of parts'), ('PAY_OF_CARD', 'Pay of card')], default='CREDIT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED_FOR_PROCESSING', 'Accepted for processing'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('DONE', 'Done')], default='ACCEPTED_FOR_PROCESSING', max_length=100, null=True),
        ),
    ]
