# Generated by Django 2.2.6 on 2019-10-28 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_order_id', models.CharField(max_length=20)),
                ('shipment_method', models.CharField(choices=[('NP', 'Нова Пошта'), ('JT', 'Justin'), ('CP', 'Самовывоз')], default='CP', max_length=2)),
                ('payment_method', models.CharField(choices=[('POD', 'Payment on delivery'), ('INP', 'Instant Payment'), ('CTC', 'Card to Card payment'), ('CTF', 'Certificate payment')], default='INP', max_length=3)),
                ('delivery_address', models.CharField(max_length=200)),
                ('shipment_status_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='status_date')),
            ],
        ),
    ]
