# Generated by Django 2.2.4 on 2019-11-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_auto_20191113_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_status_date', models.DateTimeField(auto_created=True, verbose_name='status_date')),
                ('shipment_provider', models.CharField(choices=[('Nova Poshta', 'Nova Poshta'), ('Justin', 'Justin'), ('Pickup', 'Pickup')], default='Pickup', max_length=20)),
                ('delivery_address', models.CharField(default=None, max_length=100, null=True)),
                ('post_branch', models.CharField(default=None, max_length=200, null=True)),
                ('status_change_date', models.DateTimeField(auto_now=True, verbose_name='status_change_date')),
                ('shipment_status', models.IntegerField(choices=[(1, 'Нова пошта очікує надходження від відправника'), (2, 'Видалено'), (3, 'Номер не знайдено'), (4, 'Відправлення у місті <django.db.models.fields.CharField>'), (41, 'Відправлення у місті <django.db.models.fields.CharField>'), (5, 'Відправлення прямує до міста'), (6, 'Відправлення у місті <django.db.models.fields.CharField>, орієнтовна доставка до ВІДДІЛЕННЯ-<django.db.models.fields.CharField> Очікуйте додаткове повідомлення про прибуття.'), (7, 'Прибув на відділення'), (8, 'Прибув на відділення'), (9, 'Відправлення отримано'), (10, 'Відправлення отримано <django.db.models.fields.DateTimeField>. Протягом доби ви одержите SMS-повідомлення про надходження грошового переказу та зможете отримати його в касі відділення «Нова пошта»'), (11, 'Відправлення отримано <django.db.models.fields.DateTimeField>. Грошовий переказ видано одержувачу.'), (14, 'Відправлення передано до огляду отримувачу'), (101, 'На шляху до одержувача'), (102, 'Відмова одержувача'), (103, 'Відмова одержувача'), (108, 'Відмова одержувача'), (104, 'Змінено адресу'), (105, 'Припинено зберігання'), (106, 'Одержано і створено ЄН зворотньої доставки')], default=1)),
                ('invoice_id', models.CharField(default=None, max_length=200, null=True)),
                ('public_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Order')),
            ],
            options={
                'ordering': ['public_order'],
                'unique_together': {('public_order', 'delivery_address')},
            },
        ),
    ]
