# Generated by Django 2.2.6 on 2019-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshipment',
            name='invoice_id',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='DocumentNumber'),
        ),
    ]
