# Generated by Django 2.2.6 on 2019-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_status',
            field=models.IntegerField(default=1),
        ),
    ]
