# Generated by Django 2.2.4 on 2019-11-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshipment',
            name='public_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='baseshipment',
            name='shipment_status_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='status_date'),
        ),
    ]
