# Generated by Django 2.2.4 on 2019-11-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20191114_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshipment',
            name='public_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_shipment', to='orders.Order'),
        ),
    ]
