# Generated by Django 2.2.4 on 2019-11-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20191115_1528'),
        ('shipments', '0003_auto_20191116_0756'),
    ]

    operations = [
    ]
