# Generated by Django 2.2.6 on 2019-11-24 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191121_1753'),
        ('shipments', '0004_merge_20191121_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change_date', models.DateTimeField(auto_created=True, verbose_name='status_date_change')),
                ('shipment_provider', models.CharField(choices=[('Nova Poshta', 'Nova Poshta'), ('Justin', 'Justin'), ('Pickup', 'Pickup')], default='Pickup', max_length=20)),
                ('delivery_address', models.CharField(default=None, max_length=100, null=True)),
                ('post_branch', models.CharField(default=None, max_length=200, null=True)),
                ('shipment_status_date', models.DateTimeField(auto_now=True, verbose_name='status_date')),
                ('shipment_status', models.IntegerField(choices=[(1, 'Нова пошта очікує надходження від відправника'), (2, 'Видалено'), (3, 'Номер не знайдено'), (4, 'Відправлення у місті Kyiv'), (41, 'Відправлення у місті Kyiv'), (5, 'Відправлення прямує до міста'), (6, 'Відправлення у місті Kyiv, орієнтовна доставка до ВІДДІЛЕННЯ-0001 Очікуйте додаткове повідомлення про прибуття.'), (7, 'Прибув на відділення'), (8, 'Прибув на відділення'), (9, 'Відправлення отримано'), (10, 'Відправлення отримано 01.01.2020. Протягом доби ви одержите SMS-повідомлення про надходження грошового переказу та зможете отримати його в касі відділення «Нова пошта»'), (11, 'Відправлення отримано 01.01.2020. Грошовий переказ видано одержувачу.'), (14, 'Відправлення передано до огляду отримувачу'), (101, 'На шляху до одержувача'), (102, 'Відмова одержувача'), (103, 'Відмова одержувача'), (108, 'Відмова одержувача'), (104, 'Змінено адресу'), (105, 'Припинено зберігання'), (106, 'Одержано і створено ЄН зворотньої доставки')], default=1)),
                ('invoice_id', models.CharField(default=None, max_length=200, null=True, verbose_name='DocumentNumber')),
                ('public_id', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_shipment', to='orders.Order')),
            ],
            options={
                'ordering': ['public_id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='Send Date')),
                ('log_field', models.TextField(blank=True, null=True, verbose_name='Log')),
                ('request', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Request')),
                ('is_processed', models.BooleanField(verbose_name='Is request processed')),
                ('public_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_shipment_log', to='shipments.Shipment')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseShipment',
        ),
    ]
