# Generated by Django 2.2.6 on 2019-11-01 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipments', '0004_auto_20191031_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_method', models.CharField(choices=[('NP', 'Нова Пошта'), ('JT', 'Justin'), ('CP', 'Самовывоз')], default='CP', max_length=2)),
                ('delivery_address', models.CharField(max_length=200)),
                ('shipment_status', models.IntegerField(choices=[(1, 'Нова пошта очікує надходження від відправника'), (2, 'Видалено'), (3, 'Номер не знайдено'), (4, 'Відправлення у місті Kyiv'), (41, 'Відправлення у місті Kyiv'), (5, 'Відправлення прямує до міста'), (6, 'Відправлення у місті Kyiv, орієнтовна доставка до ВІДДІЛЕННЯ-Branch #1 01-12-2019 12:00:00 Очікуйте додаткове повідомлення про прибуття.'), (7, 'Прибув на відділення'), (8, 'Прибув на відділення'), (9, 'Відправлення отримано'), (10, 'Відправлення отримано 02-12-2019 12:00:00. Протягом доби ви одержите SMS-повідомлення про надходження грошового переказу та зможете отримати його в касі відділення «Нова пошта»'), (11, 'Відправлення отримано 02-12-2019 12:00:00. Грошовий переказ видано одержувачу.'), (14, 'Відправлення передано до огляду отримувачу'), (101, 'На шляху до одержувача'), (102, 'Відмова одержувача'), (103, 'Відмова одержувача'), (108, 'Відмова одержувача'), (104, 'Змінено адресу'), (105, 'Припинено зберігання'), (106, 'Одержано і створено ЄН зворотньої доставки')], default=1)),
                ('shipment_status_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='status_date')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.BaseShipment')),
                ('pub_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem')),
            ],
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
