# Generated by Django 2.2.4 on 2019-11-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_merge_20191117_1350'),
        ('shipments', '0004_merge_20191121_1734'),
    ]

    operations = [
    ]
