# Generated by Django 2.2.6 on 2019-11-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20191101_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshipment',
            name='delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
