# Generated by Django 2.2.4 on 2019-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20191124_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='shipmentlog',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_area',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_area_region',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_flat',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_house',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_street',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmentlog',
            name='response_status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice_id',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='shipmentlog',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name='Request'),
        ),
    ]
