# Generated by Django 2.2.6 on 2019-11-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20191101_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseshipment',
            old_name='delivery_id',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='baseshipment',
            old_name='pub_order_id',
            new_name='pub_order',
        ),
    ]
