# Generated by Django 2.2.6 on 2019-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20191218_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_address',
            new_name='delivery_address_area',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_area_region',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_flat',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_house',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_street',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
