# Generated by Django 2.2.6 on 2019-12-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20191219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentlog',
            name='response_status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
